# Site settings
title:
  en: "Robert Marz, Databee - The IT-Architects"
  de: "Robert Marz, Databee - Die IT-Architekten"
email: robert.marz@databee.org
mobile: "+49 (172) 139 1530"
favicon: /images/Wolke.png
logo:
footer_logo:
description:
  en: "Robert Marz, Databee - The IT-Architects"
  de: "Robert Marz, Databee - Die IT-Architekten"
about:
  en: "About Robbie"
  de: "Über Robbie"
owner:
  name: Databee - Die IT-Architekten # or company name
  url: "https://robbie.databee.org" # your URL
copyright:
  en: "&copy; 2022 <a href='http://www.databee.org'>Databee - Die IT-Architekten</a>. All rights reserved."
  de: "&copy; 2022 <a href='http://www.databee.org'>Databee - Die IT-Architekten</a>. All rights reserved."
imprint:
  en:
    title: "Imprint - Site Notice"
    url: "/en/imprint/"
  de:
    title: "Impressum"
    url: "/de/impressum/"
dsgvo:
  en:
    title: "GDPR Information - (German only)"
    url: "/en/gdpr/"
  de:
    title: "Datenschutzerklärung"
    url: "/de/dsgvo/"
contact:
  en:
    title: "Contact me"
    url: "/en/contact/"
  de:
    title: "Kontaktieren Sie mich"
    url: "/de/kontakt/"
url: "https://robbie.databee.org" # the base hostname & protocol for this site
baseurl: "/" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
index:
  en: /en/index.html
  de: /de/index.html

# Language Setting
lang: en
languages: ["en", "de"]

#Atom Feed
feed:
  posts_limit: 100


# Enable or disable the site search
search_enabled: true

# Build settings
permalink: pretty
kramdown:
  html_to_native: true
  # parse markdown inside block-level HTML tag
  # parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

collections:
  project:
    output: true
  talks:
    output: true
    permalink: /:collection/:title
  publications:
    output: true
  events:
    output: true
  skills:
    output: true
  conferences:
    output: true

defaults:
  -
    scope:
      path: "/videos/*"
    values:
      layout: detail-video
  -
    scope:
      path: "/talks/*"
    values:
      lang: en
  -
    scope:
      path: /en/
    values:
        lang: en
        base-url: "/en/"
  -
    scope:
      path: /de/
    values:
      lang: de
      base-url: "/de/"
  -
    scope:
      path: ""
    values:
      author: Robert Marz

whitelist:
  - jekyll-redirect-from
github: [metadata]
exclude:
  - ".jekyll-cache"
  - "LICENSE.txt"
  - "README.md"
include:
  - "_pages"

plugins_dir: "_scripts"

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - github-pages
