# Site settings
title:
  en: "Robert Marz, Databee - The IT-Architects"
  de: "Robert Marz, Databee - Die IT-Architekten"
email: robert.marz@databee.org
mobile: "+49 (172) 139 1530"
favicon: /images/bee.png
logo:
footer_logo:
description:
  en: "Robert Marz, Databee - The IT-Architects"
  de: "Robert Marz, Databee - Die IT-Architekten"
about:
  en: "About Robbie"
  de: "Über Robbie"
owner:
  name: Databee - Die IT-Architekten # or company name
  url: "https://robbie.databee.org" # your URL
copyright:
  en: "&copy; 2020 <a href='#'>https://www.databee.org</a>. All rights reserved."
  de: "&copy; 2020 <a href='#'>https://www.databee.org</a>. All rights reserved."
url: "https://robbie.databee.org" # the base hostname & protocol for this site
baseurl: "/" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
index:
  en: index.html
  de: indexde.html

# Language Setting
lang: de
languages: ["en", "de"]

# Enable or disable the site search
search_enabled: true

# Social handle for website
social:
  twitter:   https://twitter.com/RobbieDatabee
  linkedin:  https://www.linkedin.com/in/robbiedatabee/
  xing:      https://www.xing.com/profile/Robert_Marz/cv
  #pinterest   : https://www.pinterest.com/#/
  #instagram   : https://www.instagram.com/#/
  #facebook    : https://facebook.com/#
  #dribbble:
  #vine:
  #flickr:
  #skype:
  #tumblr:
  #youtube:

# Build settings
permalink: pretty
kramdown:
  # parse markdown inside block-level HTML tag
  # parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

exclude: ["LICENSE.txt", "README.md"]
include: ['_pages']

collections:
  project:
    output: false
  talks:
    output: true
    permalink: /:collection/:title
  services:
    output: false
  publications:
    output: false
  events:
    output: false
  skills:
    output: false

defaults:
    -
     scope:
         path: ""
     values:
         layout: post
         lang: en
         base-url: "/"
    -
     scope:
         path: de
     values:
         lang: de
         base-url: "/de/"


# Plugins
plugins_dir:
  - jekyll-feed
  - github-pages
