# Site settings
title:
  en: Robert Marz, Databee - The IT-Architects
  de: Robert Marz, Databee - Die IT-Architekten
email: robert.marz@databee.org
mobile: +49 (172) 139 1530
favicon: /images/bee.png
logo: /images/Databee-Logo.jpg
footer_logo:
description:
  en: Description goes here
  de: Beschreibung hier einfügen
about:
  en: about (en)
  de: abput (de)
owner:
  name: Robert Marz, Databee - Die IT-Architekten
  url: "https://robbie.databee.org" 
copyright:
  en: "&copy; 2019 <a href='#'>Robert Marz</a>. All rights reserved. Created by <a href='#'>LocalSolutionsDev</a>"
  de: "&copy; 2019 <a href='#'>Robert Marz</a>. All rights reserved. Created by <a href='#'>LocalSolutionsDev</a>"
url: "http://127.0.0.1:4000" # the base hostname & protocol for this site
baseurl: "/" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
index:
  en:
  de: indexde.html

# Language Setting
lang: en
languages: ["en", "de"]

# Enable or disable the site search
search_enabled: true

# Social handle for website
social:
  #facebook    : https://facebook.com/#
  twitter     : https://twitter.com/RobbieDatabee
  #pinterest   : https://www.pinterest.com/#/
  linkedin    : https://linkedin.com/in/RobbieDatabee
  xing:         https://linkedin.com/in/RobbieDatabee
  #instagram   : https://www.instagram.com/#/
  #dribbble:
  #vine:
  #flickr:
  #skype:
  #tumblr:
  #youtube:

# Build settings
permalink: pretty
kramdown:
  # parse markdown inside block-level HTML tag
  # parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

exclude: ["LICENSE.txt", "README.md"]
include: ['_pages']

collections:
  project:
    output: true
  talks:
    output: true
    permalink: /:collection/:title
  services:
    output: true
  publications:
    output: true
  events:
    output: true
  skills:
    output: true

defaults:
    -
     scope:
         path: ""
     values:
         layout: post
         lang: en
         base-url: "/"
    -
     scope:
         path: de
     values:
         lang: de
         base-url: "/de/"


# Plugins
plugins_dir:
  - jekyll-feed
  - github-pages
