#
# Be aware that even a small syntax error here can lead to failures in output.
#
# Home Page Services
languages:
  - language: "de"
    services:
      - heading: Mein Dienstleistungsportfolio
        subheading: Diese Dienstleistungen können Sie von mir beziehen
  - language: "en"
    services:
      - heading: My Service Portfolio
        subheading: Order these Services from me
